apiVersion: v2
appVersion: "1.0"
name: mysql
description: A Helm chart for MySQL
type: application
version: 0.1.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common
