apiVersion: v2
appVersion: "1.0"
name: review
description: A Helm chart for the Review microservice
type: application
version: 1.0.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common