fullnameOverride: mongodb

image:
  repository: registry.hub.docker.com/library
  name: mongod
  tag: 4.4.2
  pullPolicy: IfNotPresent

ports:
  - containerPort: 27017

service:
  ports:
    - port: 27017