secrets:
  rabbitmq-server-credentials:
    RABBITMQ_DEFAULT_USER: rabbit-user-dev
    RABBITMQ_DEFAULT_PASS: rabbit-pwd-dev

  rabbitmq-credentials:
    SPRING_RABBITMQ_USERNAME: rabbit-user-dev
    SPRING_RABBITMQ_PASSWORD: rabbit-pwd-dev

  rabbitmq-zipkin-credentials:
    RABBIT_USER: rabbit-user-dev
    RABBIT_PASSWORD: rabbit-pwd-dev

  mongodb-server-credentials:
    MONGO_INITDB_ROOT_USERNAME: mongodb-user-dev
    MONGO_INITDB_ROOT_PASSWORD: mongodb-pwd-dev

  mongodb-credentials:
    SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    SPRING_DATA_MONGODB_USERNAME: mongodb-user-dev
    SPRING_DATA_MONGODB_PASSWORD: mongodb-pwd-dev

  postgres-server-credentials:
    POSTGRES_DB: review_db
    POSTGRES_USER: postgres-user-dev
    POSTGRES_PASSWORD: postgres-pwd-dev

  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: postgres-user-dev
    SPRING_DATASOURCE_PASSWORD: postgres-pwd-dev

rabbitmq:
  envFromSecretRefs:
    - rabbitmq-server-credentials

mongodb:
  envFromSecretRefs:
    - mongodb-server-credentials

postgresql:
  envFromSecretRefs:
    - postgres-server-credentials

auth-server:
  envFromSecretRefs:
    - rabbitmq-credentials

product:
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials

recommendation:
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials

review:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials

product-composite:
  envFromSecretRefs:
    - rabbitmq-credentials

zipkin-server:
  envFromSecretRefs:
    - rabbitmq-zipkin-credentials
