version: "3.7"

services:
  license-service:
    image: case-study-microservices/license-service
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "license-service"

networks:
  backend:
    driver: bridge