version: "2.1"

services:
  database:
    image: postgres:latest
    ports:
      - "8050:5432"
    environment:
      POSTGRES_USER: "ostock"
      POSTGRES_PASSWORD:  "password"
      POSTGRES_DB: "ostock"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-service:
    image: case-study-microservices/config-service
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-service"

  eureka-service:
    image: case-study-microservices/eureka-service
    ports:
      - "8070:8070"
    depends_on:
      database:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eureka-service"

  license-service:
    image: case-study-microservices/license-service
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URL: "http://config-service:8071"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"
    depends_on:
      database:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      - backend

  organization-service:
    image: case-study-microservices/organization-service
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"
    depends_on:
      database:
        condition: service_healthy
      config-service:
        condition: service_started
    ports:
      - "8080:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge