apiVersion: v2
appVersion: "1.0"
name: postgresql
description: A Helm chart for PostgreSQL
type: application
version: 1.0.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common
