fullnameOverride: postgresql

image:
  repository: registry.hub.docker.com/library
  name: postgres
  tag: 14.0
  pullPolicy: IfNotPresent

ports:
  - containerPort: 3306

service:
  ports:
    - port: 3306