example:
  property: I AM THE DEFAULT

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  database:
    driverClassName: org.postgresql.Driver

  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1

management:
  enpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true