apiVersion: v2
name: gateway
description: A Helm chart for the Spring Cloud Gateway
version: 1.0.0
type: application
appVersion: "1.0"

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common
