{{- define "common.deployment" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValue := omit . "Values" }}
{{- with merge $noValue $overrides $common -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "common.name" . }}
    helm.sh/chart: {{ include "common.chart" .}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.name" . }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.name" .}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # Arguments
          {{- with .Values.image.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          # Environment variables
          {{- if .Values.env  }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end }}
          {{- end }}

          # Environment variables from secret references
          {{- if .Values.envFromSecretRefs  }}
          envFrom:
            {{- range .Values.envFromSecretRefs }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}

          # Liveness Probe
          {{- if .Values.livenessProbe_enabled  }}
          livenessProbe:
            {{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}

          # Readiness Probe
          {{- if.Values.readnessProbe_enabled }}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}

          # Ports
          ports:
            {{ toYaml .Values.ports | indent 12 }}

          # Resources
          resources:
            {{ toYaml .Values.resources | indent 12 }}

      # Configmap
      {{- if .Values.configmap.enabled  }}
          volumeMounts:
            - mountPath: {{ .Values.configmap.volumeMounts.mountPath }}
              name: {{ include "common.fullname" .}}
      volumes:
        - name: {{ include "common.fullname" . }}
          configMap:
            name: {{ include "common.fullname" .}}
      {{- end }}
{{- end -}}
{{- end -}}