apiVersion: v2
name: configuration
description: A Helm chart for Config server
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common
