apiVersion: v2
name: authorization
description: A Helm chart for Authorization Server
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common
