apiVersion: v2
name: auth-server
description: A Helm chart for Auth Server
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common
