apiVersion: v2
appVersion: "1.0"
name: recommendation
description: A Helm chart for the Recommendation microservice
type: application
version: 0.1.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common
